name: Build Packages
on:
  workflow_dispatch:
    inputs:
      packages:
        description: "Packages to Build (pkg-a, pkg-b, ...)"
        required: true

jobs:
  parse:
    outputs:
      pkgs: ${{ steps.parsing.outputs.pkgs }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Parse Input
        id: parsing
        run: echo "${{ inputs.packages }}" | sed 's/ /\n/g' | sed 's/$/\//g' | jq -R . | jq -s . | jq -c . | sed 's/^/::set-output name=pkgs::/'
  build:
    needs: parse
    strategy:
      matrix:
        pkg: ${{ fromJson(needs.parse.outputs.pkgs) }}
        version: ["terra37"]
        arch: ["x86_64", "aarch64"]
      fail-fast: false
    runs-on: ${{ matrix.arch == 'aarch64' && 'ARM64' || 'ubuntu-latest' }}
    container:
      image: registry.fedoraproject.org/fedora:37
      options: --cap-add=SYS_ADMIN --privileged
    steps:
      - name: Install repositories
        run: |
          sudo dnf install -y dnf-plugins-core
          sudo dnf config-manager --add-repo https://github.com/andaman-common-pkgs/subatomic-repos/raw/main/terra37.repo
          sudo dnf install -y anda-mock-configs subatomic-cli anda mock rpm-build mock-scm

      - uses: terrapkg/anda-build@main
        with:
          name: "${{ matrix.pkg }}pkg"
          mockConfig: anda-37-${{ matrix.arch }}
          extraArgs: -D "sccache_bucket ${{secrets.SCCACHE_BUCKET}}" -D "sccache_endpoint ${{secrets.SCCACHE_ENDPOINT}}" -D "sccache_secret ${{secrets.SCCACHE_SECRET}}" -D "sccache_accesskey ${{secrets.SCCACHE_ACCESSKEY}}"
          andaRepo: https://github.com/andaman-common-pkgs/subatomic-repos/raw/main/terra37.repo

      - name: Install Subatomic client
        run: sudo dnf install -y subatomic-cli

      - name: Upload packages to subatomic
        run: |
          subatomic-cli upload --prune \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            ${{ matrix.version }} anda-build/rpm/rpms/*
