name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: registry.fedoraproject.org/fedora:37
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dnf install -y rpmlint
      - name: Lint spec files
        run: rpmlint $(find anda -type f -name "*.spec" -type f)
