name: Push comps updates

on:
  push:
    branches:
      - el9
    paths:
      - comps.xml
  workflow_dispatch:

jobs:
  update-comps:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/terrapkg/builder:frawhide
    steps:
      - uses: actions/checkout@v4
      - name: Push to subatomic
        run: |
          branch=${{ github.ref_name }}
          subatomic-cli upload-comps \
            --server https://subatomic.fyralabs.com \
            --token ${{ secrets.SUBATOMIC_TOKEN }} \
            "terra-${branch}" comps.xml
